server:
  port: ${PORT:0}

spring:
  application:
    name: product

eureka:
  instance:
    appname: product
    #    metadata-map:
    #      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

info:
  app:
    name: Product Sample Application
    description: Description
    version: 1.0.0

management:
  endpoint:
    configprops:
      enabled: true
    health:
      show-details: always

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full